import dotenv from "dotenv";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import rateLimit from "express-rate-limit";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { Pool } from "pg";
import { z } from "zod";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../.env") });

const port = Number(process.env.PORT || 4000);
const jwtSecret = process.env.JWT_SECRET;
if (!jwtSecret && process.env.NODE_ENV === "production") throw new Error("JWT_SECRET is required in production");

const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 20, idleTimeoutMillis: 30_000 });
async function testDatabaseConnection() {
  try {
    const result = await pool.query("SELECT 1 AS connected");

    console.log("✅ PostgreSQL connected successfully");
    console.log("DB response:", result.rows[0]);
  } catch (error) {
    console.error("❌ PostgreSQL connection failed");
    console.error(error.message);
    process.exit(1);
  }
}
const app = express();
app.use(helmet());
const allowedOrigins = new Set((process.env.CLIENT_ORIGIN || "http://localhost:5173").split(",").map(origin => origin.trim()).filter(Boolean));
app.use(cors({ origin: (origin, callback) => { const isLocalDevelopment = process.env.NODE_ENV !== "production" && /^https?:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin || ""); if (!origin) callback(null, true); else if (allowedOrigins.has(origin) || isLocalDevelopment) callback(null, origin); else callback(new Error("Origin is not allowed by CORS")); } }));
app.use(express.json({ limit: "100kb" }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: true, legacyHeaders: false }));

const productInput = z.object({ name: z.string().trim().min(1).max(160), sku: z.string().trim().min(1).max(80), purchasePrice: z.coerce.number().finite().nonnegative(), salePrice: z.coerce.number().finite().nonnegative(), stock: z.coerce.number().finite().nonnegative().default(0), unit: z.string().trim().min(1).max(40).default("Piece") });
const productUpdateInput = z.object({ purchasePrice: z.coerce.number().finite().nonnegative(), salePrice: z.coerce.number().finite().nonnegative(), stock: z.coerce.number().finite().nonnegative() });
const itemInput = z.object({ productId: z.coerce.number().int().positive(), qty: z.coerce.number().finite().positive(), price: z.coerce.number().finite().nonnegative() });
const purchaseInput = z.object({ supplier: z.string().trim().min(1).max(160), date: z.coerce.date(), items: z.array(itemInput).min(1).max(200) });
const saleInput = z.object({ customer: z.string().trim().min(1).max(160), mobile: z.string().regex(/^\d{10}$/), date: z.coerce.date(), items: z.array(itemInput).min(1).max(200), paymentMode: z.enum(["cash", "upi", "partial"]), paidAmount: z.coerce.number().finite().nonnegative(), paymentMethod: z.enum(["cash", "upi"]), dueDate: z.coerce.date().optional(), paymentNotes: z.string().trim().max(500).optional() }).superRefine((input, ctx) => { const total = input.items.reduce((sum, item) => sum + item.qty * item.price, 0); if (input.paymentMode !== "partial" && input.paidAmount !== total) ctx.addIssue({ code: "custom", path: ["paidAmount"], message: "Cash and UPI payments must equal the sale total" }); if (input.paidAmount > total) ctx.addIssue({ code: "custom", path: ["paidAmount"], message: "Paid amount cannot exceed the sale total" }); if (input.paymentMode === "partial" && input.paidAmount < total && !input.dueDate) ctx.addIssue({ code: "custom", path: ["dueDate"], message: "Due date is required for pay-later sales" }); });
const paymentInput = z.object({ amount: z.coerce.number().finite().positive(), paymentMethod: z.enum(["cash", "upi"]), paymentDate: z.coerce.date(), notes: z.string().trim().max(500).optional() });
const credentials = z.object({ username: z.string().trim().min(1).max(200), password: z.string().min(8).max(200) });

const money = value => Number(value);
const dateOnly = value => new Date(value).toISOString().slice(0, 10);
const productDto = row => ({ id: Number(row.id), name: row.name, sku: row.sku, purchasePrice: money(row.purchase_price), salePrice: money(row.sale_price), stock: money(row.stock), unit: row.unit });
async function transaction(work) { const client = await pool.connect(); try { await client.query("BEGIN"); const result = await work(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
function requireAuth(req, res, next) { if (process.env.REQUIRE_AUTH !== "true") return next(); const token = req.headers.authorization?.replace(/^Bearer\s+/, ""); try { req.user = jwt.verify(token, jwtSecret); next(); } catch { res.status(401).json({ error: "Authentication required" }); } }
function asyncRoute(handler) { return (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next); }

app.get("/api/health", asyncRoute(async (_req, res) => { await pool.query("SELECT 1"); res.json({ status: "ok" }); }));
app.post("/api/auth/login", asyncRoute(async (req, res) => {console.log({req:req.body});  const input = credentials.parse(req.body); const { rows } = await pool.query("SELECT id, email, password_hash FROM users WHERE email = $1", [input.username.toLowerCase()]); const user = rows[0]; if (!user || !(await bcrypt.compare(input.password, user.password_hash))) return res.status(401).json({ error: "Invalid username or password" }); res.json({ token: jwt.sign({ sub: user.id, email: user.email }, jwtSecret || "development-secret", { expiresIn: "8h" }), user: { id: Number(user.id), username: user.email } }); }));

app.get("/api/products", requireAuth, asyncRoute(async (_req, res) => { const { rows } = await pool.query("SELECT * FROM products ORDER BY name"); res.json(rows.map(productDto)); }));
app.post("/api/products", requireAuth, asyncRoute(async (req, res) => { const input = productInput.parse(req.body); const { rows } = await pool.query("INSERT INTO products (name, sku, purchase_price, sale_price, stock, unit) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *", [input.name, input.sku, input.purchasePrice, input.salePrice, input.stock, input.unit]); res.status(201).json(productDto(rows[0])); }));
app.patch("/api/products/:id", requireAuth, asyncRoute(async (req, res) => { const input = productUpdateInput.parse(req.body); const { rows } = await pool.query("UPDATE products SET purchase_price = $1, sale_price = $2, stock = $3, updated_at = NOW() WHERE id = $4 RETURNING *", [input.purchasePrice, input.salePrice, input.stock, req.params.id]); if (!rows[0]) return res.status(404).json({ error: "Product not found" }); res.json(productDto(rows[0])); }));

app.get("/api/purchases", requireAuth, asyncRoute(async (_req, res) => { const { rows } = await pool.query("SELECT p.*, COALESCE(json_agg(json_build_object('productId', i.product_id, 'qty', i.qty, 'price', i.price)) FILTER (WHERE i.id IS NOT NULL), '[]') AS items FROM purchases p LEFT JOIN purchase_items i ON i.purchase_id = p.id GROUP BY p.id ORDER BY p.purchase_date DESC, p.id DESC"); res.json(rows.map(row => ({ id: Number(row.id), supplier: row.supplier, date: dateOnly(row.purchase_date), total: money(row.total), items: row.items.map(item => ({ ...item, productId: Number(item.productId), qty: money(item.qty), price: money(item.price) })) }))); }));
app.post("/api/purchases", requireAuth, asyncRoute(async (req, res) => { const input = purchaseInput.parse(req.body); const result = await transaction(async client => { const ids = [...new Set(input.items.map(item => item.productId))]; const { rows: products } = await client.query("SELECT * FROM products WHERE id = ANY($1::bigint[]) FOR UPDATE", [ids]); if (products.length !== ids.length) throw Object.assign(new Error("One or more products do not exist"), { status: 400 }); const byId = new Map(products.map(product => [Number(product.id), product])); const items = input.items.map(item => ({ ...item, product: byId.get(item.productId), lineTotal: item.qty * item.price })); const total = items.reduce((sum, item) => sum + item.lineTotal, 0); const { rows: purchases } = await client.query("INSERT INTO purchases (supplier, purchase_date, total) VALUES ($1,$2,$3) RETURNING id, purchase_date", [input.supplier, dateOnly(input.date), total]); const purchase = purchases[0]; for (const item of items) { await client.query("INSERT INTO purchase_items (purchase_id, product_id, qty, price, line_total) VALUES ($1,$2,$3,$4,$5)", [purchase.id, item.productId, item.qty, item.price, item.lineTotal]); await client.query("UPDATE products SET stock = stock + $1, purchase_price = $2, updated_at = NOW() WHERE id = $3", [item.qty, item.price, item.productId]); } return { id: Number(purchase.id), supplier: input.supplier, date: dateOnly(purchase.purchase_date), items: input.items, total }; }); res.status(201).json(result); }));

app.get("/api/sales", requireAuth, asyncRoute(async (_req, res) => { const { rows } = await pool.query("SELECT s.*, COALESCE(json_agg(json_build_object('productId', i.product_id, 'qty', i.qty, 'price', i.price)) FILTER (WHERE i.id IS NOT NULL), '[]') AS items FROM sales s LEFT JOIN sale_items i ON i.sale_id = s.id GROUP BY s.id ORDER BY s.sale_date DESC, s.id DESC"); res.json(rows.map(row => ({ id: Number(row.id), customer: row.customer, mobile: row.mobile, date: dateOnly(row.sale_date), total: money(row.total), profit: money(row.profit), items: row.items.map(item => ({ ...item, productId: Number(item.productId), qty: money(item.qty), price: money(item.price) })) }))); }));
app.post("/api/sales", requireAuth, asyncRoute(async (req, res) => { const input = saleInput.parse(req.body); const result = await transaction(async client => { const ids = [...new Set(input.items.map(item => item.productId))]; const { rows: products } = await client.query("SELECT * FROM products WHERE id = ANY($1::bigint[]) FOR UPDATE", [ids]); if (products.length !== ids.length) throw Object.assign(new Error("One or more products do not exist"), { status: 400 }); const byId = new Map(products.map(product => [Number(product.id), product])); const quantities = new Map(); for (const item of input.items) quantities.set(item.productId, (quantities.get(item.productId) || 0) + item.qty); for (const [id, qty] of quantities) { const product = byId.get(id); if (qty > money(product.stock)) throw Object.assign(new Error(`${product.name}: only ${product.stock} ${product.unit} available`), { status: 409 }); } const items = input.items.map(item => { const product = byId.get(item.productId); const lineTotal = item.qty * item.price; return { ...item, costPrice: money(product.purchase_price), lineTotal, lineProfit: item.qty * (item.price - money(product.purchase_price)) }; }); const total = items.reduce((sum, item) => sum + item.lineTotal, 0); const profit = items.reduce((sum, item) => sum + item.lineProfit, 0); const status = input.paidAmount === total ? "paid" : "pending"; const { rows: sales } = await client.query("INSERT INTO sales (customer, mobile, sale_date, total, profit, paid_amount, payment_status, due_date, payment_method, payment_notes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, sale_date", [input.customer, input.mobile, dateOnly(input.date), total, profit, input.paidAmount, status, input.dueDate ? dateOnly(input.dueDate) : null, input.paymentMethod, input.paymentNotes || null]); const sale = sales[0]; for (const item of items) { await client.query("INSERT INTO sale_items (sale_id, product_id, qty, price, cost_price, line_total, line_profit) VALUES ($1,$2,$3,$4,$5,$6,$7)", [sale.id, item.productId, item.qty, item.price, item.costPrice, item.lineTotal, item.lineProfit]); await client.query("UPDATE products SET stock = stock - $1, updated_at = NOW() WHERE id = $2", [item.qty, item.productId]); } return { id: Number(sale.id), customer: input.customer, mobile: input.mobile, date: dateOnly(sale.sale_date), items: input.items, total, profit, paidAmount: input.paidAmount, remainingAmount: total - input.paidAmount, paymentStatus: status, dueDate: input.dueDate ? dateOnly(input.dueDate) : null, paymentMethod: input.paymentMethod, paymentNotes: input.paymentNotes || "" }; }); res.status(201).json(result); }));

app.get("/api/pay-later", requireAuth, asyncRoute(async (_req, res) => { const { rows } = await pool.query("SELECT s.*, COALESCE(json_agg(json_build_object('productId', i.product_id, 'qty', i.qty, 'price', i.price)) FILTER (WHERE i.id IS NOT NULL), '[]') AS items, COALESCE((SELECT json_agg(json_build_object('id', p.id, 'amount', p.amount, 'paymentMethod', p.payment_method, 'paymentDate', p.payment_date, 'notes', p.notes) ORDER BY p.payment_date DESC, p.id DESC) FROM pay_later_payments p WHERE p.sale_id = s.id), '[]') AS payments FROM sales s LEFT JOIN sale_items i ON i.sale_id = s.id WHERE s.payment_status = 'pending' GROUP BY s.id ORDER BY s.due_date ASC NULLS LAST, s.id DESC"); res.json(rows.map(row => ({ id: Number(row.id), customer: row.customer, mobile: row.mobile, date: dateOnly(row.sale_date), total: money(row.total), profit: money(row.profit), paidAmount: money(row.paid_amount), remainingAmount: money(row.total) - money(row.paid_amount), dueDate: row.due_date ? dateOnly(row.due_date) : null, paymentMethod: row.payment_method, paymentNotes: row.payment_notes || "", items: row.items.map(item => ({ ...item, productId: Number(item.productId), qty: money(item.qty), price: money(item.price) })), payments: row.payments.map(payment => ({ ...payment, id: Number(payment.id), amount: money(payment.amount), paymentDate: dateOnly(payment.paymentDate) })) }))); }));
app.post("/api/pay-later/:saleId/payments", requireAuth, asyncRoute(async (req, res) => { const input = paymentInput.parse(req.body); const result = await transaction(async client => { const { rows } = await client.query("SELECT id, total, paid_amount, payment_status FROM sales WHERE id = $1 FOR UPDATE", [req.params.saleId]); const sale = rows[0]; if (!sale) throw Object.assign(new Error("Pay-later sale not found"), { status: 404 }); const remaining = money(sale.total) - money(sale.paid_amount); if (input.amount > remaining) throw Object.assign(new Error(`Payment cannot exceed the remaining balance of ${remaining}`), { status: 400 }); await client.query("INSERT INTO pay_later_payments (sale_id, amount, payment_method, payment_date, notes) VALUES ($1,$2,$3,$4,$5)", [sale.id, input.amount, input.paymentMethod, dateOnly(input.paymentDate), input.notes || null]); const newPaidAmount = money(sale.paid_amount) + input.amount; const status = newPaidAmount === money(sale.total) ? "paid" : "pending"; await client.query("UPDATE sales SET paid_amount = $1, payment_status = $2 WHERE id = $3", [newPaidAmount, status, sale.id]); return { saleId: Number(sale.id), paidAmount: newPaidAmount, remainingAmount: money(sale.total) - newPaidAmount, paymentStatus: status }; }); res.json(result); }));

app.get("/api/summary", requireAuth, asyncRoute(async (_req, res) => { const [products, sales, purchases] = await Promise.all([pool.query("SELECT id, name, stock, unit, purchase_price FROM products ORDER BY name"), pool.query("SELECT id, customer, total, profit, sale_date FROM sales ORDER BY id DESC"), pool.query("SELECT COALESCE(SUM(total), 0) AS total FROM purchases")]); res.json({ products: products.rows.map(productDto), sales: sales.rows.map(row => ({ id: Number(row.id), customer: row.customer, total: money(row.total), profit: money(row.profit), date: dateOnly(row.sale_date) })), totalSales: sales.rows.reduce((sum, row) => sum + money(row.total), 0), totalPurchases: money(purchases.rows[0].total), profit: sales.rows.reduce((sum, row) => sum + money(row.profit), 0) }); }));

app.use((error, _req, res, _next) => { if (error instanceof z.ZodError) return res.status(400).json({ error: "Invalid request", details: error.issues }); if (error.code === "23505") return res.status(409).json({ error: "SKU or email already exists" }); res.status(error.status || 500).json({ error: error.status ? error.message : "Internal server error" }); });

async function start() { const schema = await fs.readFile(path.join(__dirname, "schema.sql"), "utf8"); await pool.query(schema); if (process.env.ADMIN_EMAIL && process.env.ADMIN_PASSWORD) { const hash = await bcrypt.hash(process.env.ADMIN_PASSWORD, 12); await pool.query("INSERT INTO users (email, password_hash) VALUES ($1, $2) ON CONFLICT (email) DO NOTHING", [process.env.ADMIN_EMAIL.toLowerCase(), hash]); } app.listen(port, () => console.log(`Mera SHOP API listening on http://localhost:${port}`)); }
start().catch(error => { console.error(error); process.exit(1); });