import { useState } from "react"; import { useERP } from "../context/ERPContext";
export default function Purchase(){
 const {products,addPurchase}=useERP(); const [supplier,setSupplier]=useState(""); const [date,setDate]=useState(new Date().toISOString().slice(0,10));
 const [items,setItems]=useState([{productId:products[0]?.id||"",qty:1,price:products[0]?.purchasePrice||0}]);
 const change=(idx,key,value)=>setItems(a=>a.map((x,i)=>i===idx?{...x,[key]:value}:x));
 const add=()=>setItems(a=>[...a,{productId:products[0]?.id||"",qty:1,price:products[0]?.purchasePrice||0}]);
 const total=items.reduce((s,i)=>s+Number(i.qty)*Number(i.price),0);
 const save=async e=>{e.preventDefault();if(!supplier||!items.length)return alert("Enter supplier and items");try{await addPurchase({supplier,date,items:items.map(i=>({...i,productId:Number(i.productId),qty:Number(i.qty),price:Number(i.price)})),total});setSupplier("");setItems([{productId:products[0]?.id||"",qty:1,price:products[0]?.purchasePrice||0}]);alert("Purchase saved and stock updated.");}catch{}};
 return <><Page title="Purchase" sub="Purchase products from wholesalers and add them to stock."/><form className="panel" onSubmit={save}><div className="form-grid"><label>Wholesaler / Supplier<input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Supplier name" required/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><h3>Purchase Items</h3><div className="table-wrap"><table><thead><tr><th>Product</th><th>Qty</th><th>Purchase Price</th><th>Total</th><th></th></tr></thead><tbody>{items.map((item,i)=><tr key={i}><td><select value={item.productId} onChange={e=>{change(i,"productId",e.target.value);const p=products.find(x=>x.id===Number(e.target.value));change(i,"price",p?.purchasePrice||0)}}>{products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></td><td><input type="number" min="1" value={item.qty} onChange={e=>change(i,"qty",e.target.value)}/></td><td><input type="number" min="0" value={item.price} onChange={e=>change(i,"price",e.target.value)}/></td><td>₹{(item.qty*item.price).toLocaleString("en-IN")}</td><td><button type="button" className="icon-btn" onClick={()=>setItems(a=>a.filter((_,n)=>n!==i))}>×</button></td></tr>)}</tbody></table></div><button type="button" className="secondary" onClick={add}>+ Add Item</button><div className="total-box"><span>Grand Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><button className="primary">Save Purchase</button></form></>;
}
function Page({title,sub}){return <div className="page-title"><div><h2>{title}</h2><p>{sub}</p></div></div>}